### ISSUE TITLE
Question about serial buffer size type.

### ISSUE THREAD

**Issue by OpusK** [lancaster-university/codal-core#114]
Hi,

As you can see in the code below, the buffer size is limited from 0 to 255 (actually up to 254).
Did you intentionally limit the size? If so, head and tail are also sufficient for uint8_t, why are they only uint16_t?
Did you have any intentions?

Personally, I want to change the buffer size to uint16_t type in consideration of scalability.

https://github.com/lancaster-university/codal-core/blob/7e459b8d7aebeef5591e636f5b5ba6d1053562f6/inc/driver-models/Serial.h#L80-L88

**Comment by jamesadevine** [comment]
Hiya @opusk,

As mentioned before the Serial abstraction was designed for the micro:bit, which has no DMA and also very little ram (16 kb). Because of its small amount of memory, drivers need to have as little static RAM overhead as possible, unless required.

Would be more than happy to move to a uint16_t all around. Right now I think the compiler would be wasting two bytes anyway for the rx/tx buffer size variable.

**Comment by OpusK** [comment]
Hi, @jamesadevine.

Thanks for the reply.
I understand why it was so designed.
As you say, depending on the device, unnecessary resources will increase. Personally, it would be nice if the user could choose the type through preprocessing and macros. In this case, if you change the type of Head and Tail to be the same as the BuffSize, you can further reduce unnecessary resources.

Apart from Macro support, if you're going to fix the BuffSize with uint8_t, it's good to change the BuffHead and BuffTail to uint8_t as well.
If so, unnecessary 4 bytes will be saved.
